In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as mp
from pylab import show
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import AdaBoostClassifier
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
import math
from numpy import genfromtxt
train = genfromtxt('/Users/wangfei/Documents/Courses/BIOE530/Final Project/HAPT Data Set/PCs.csv', 
                   delimiter=',', skip_header=1,usecols=(1,2,3))
test = genfromtxt('/Users/wangfei/Documents/Courses/BIOE530/Final Project/HAPT Data Set/PCs_test.csv', 
                   delimiter=',', skip_header=1,usecols=(1,2,3))


trainFeatures = []
traindigits = []
for row in train:
    if(row[0]==1 or row[0]==5):
        trainFeatures.append(row[1:])
        traindigits.append(str(row[0]))
testFeatures = []
testdigits = []
for row in test:
    if(row[0]==1 or row[0]==5):
        testFeatures.append(row[1:])
        testdigits.append(str(row[0]))

In [6]:
[testFeatures, testdigits]

[[array([-11.27209241,  -0.84641801]),
  array([-14.25558707,  -0.11183554]),
  array([-15.6515521 ,   3.30453407]),
  array([-15.89567567,   2.5788714 ]),
  array([-15.06647648,  -0.70108758]),
  array([-14.90996973,  -0.52265623]),
  array([-15.34331989,   1.03441603]),
  array([-16.29330985,   2.80807752]),
  array([-16.85011804,   3.45454274]),
  array([-17.20011058,   5.12934162]),
  array([-17.18375342,   5.75065493]),
  array([-17.51011704,   8.51282443]),
  array([-17.55319448,   8.23125522]),
  array([-16.86141933,   4.46330803]),
  array([-16.47950007,   2.91207254]),
  array([-13.55431236,  -2.21524514]),
  array([-13.3926403,  -4.5339381]),
  array([-15.61841532,  -1.77890668]),
  array([-15.95638953,  -0.42914519]),
  array([-12.42579466,  -1.06601472]),
  array([-12.65166939,   0.26732335]),
  array([-13.16630889,   6.44741825]),
  array([-10.42300097,   3.19721876]),
  array([-10.51453591,  -1.64533781]),
  array([-14.94638218,   0.64863508]),
  array([-15.35509164,   1.

In [18]:
####Part 2 
SVM_clf = SVC(kernel='poly',C = 38.88155180308085,degree = 2,gamma='auto').fit(trainFeatures,traindigits)
NN_clf = MLPClassifier(hidden_layer_sizes=(50,2),activation = "relu", epsilon=0.001, 
                       max_iter=10000,alpha=0, solver = "adam").fit(trainFeatures,traindigits)
RF_clf = RandomForestClassifier(criterion='entropy',max_leaf_nodes=100,n_estimators=40).fit(trainFeatures,traindigits)
AdaBoost = AdaBoostClassifier(base_estimator=DecisionTreeClassifier(criterion='entropy',
                                                                    max_depth=1),
                              n_estimators=100).fit(trainFeatures,traindigits)


KeyboardInterrupt: 

In [19]:
def bound(model):
    error = 1- model.score(testFeatures,testdigits)
    Markov_75 = error/0.25
    Markov_95 = error/0.05
    Markov_99 = error/0.01
    n = len(testdigits)
    var = error * (1-error)/n
    cheby_75 = error + math.sqrt(var/0.25)
    cheby_95 = error + math.sqrt(var/0.05)
    cheby_99 = error + math.sqrt(var/0.01)
    Hoeff_75 = error + math.sqrt(1/2/n*math.log(2/0.25))
    Hoeff_95 = error + math.sqrt(1/2/n*math.log(2/0.05))
    Hoeff_99 = error + math.sqrt(1/2/n*math.log(2/0.01))
    return np.array([Markov_75,Markov_95,Markov_99,
                    cheby_75,cheby_95,cheby_99,
                    Hoeff_75,Hoeff_95,Hoeff_99])


array([0.00380228, 0.01901141, 0.09505703, 0.00285081, 0.00519963,
       0.01045175, 0.03238825, 0.04282263, 0.05113236])

array([0.00380228, 0.01901141, 0.09505703, 0.00285081, 0.00519963,
       0.01045175, 0.03238825, 0.04282263, 0.05113236])